<?php

namespace MovLib\Data;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-21 at 22:20:39.
 */
class MovieImagesTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var MovieImages
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new MovieImages;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers MovLib\Data\MovieImages::getOrderedByCreatedAsc
   * @todo   Implement testGetOrderedByCreatedAsc().
   */
  public function testGetOrderedByCreatedAsc() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers MovLib\Data\MovieImages::getOrderedByCreatedDesc
   * @todo   Implement testGetOrderedByCreatedDesc().
   */
  public function testGetOrderedByCreatedDesc() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers MovLib\Data\MovieImages::getOrderedByUpvotes
   * @todo   Implement testGetOrderedByUpvotes().
   */
  public function testGetOrderedByUpvotes() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers MovLib\Data\MovieImages::getStreamImages
   * @todo   Implement testGetStreamImages().
   */
  public function testGetStreamImages() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers ::__construct
   * @todo Implement __construct
   */
  public function testConstruct() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

  /**
   * @covers ::initImageProperties
   * @todo Implement initImageProperties
   */
  public function testInitImageProperties() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

}
