<?php

namespace MovLib\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-21 at 22:20:31.
 */
class HandlersTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Handlers
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Handlers;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers MovLib\Exception\Handlers::errorHandler
   * @todo   Implement testErrorHandler().
   */
  public function testErrorHandler() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers MovLib\Exception\Handlers::fatalErrorHandler
   * @todo   Implement testFatalErrorHandler().
   */
  public function testFatalErrorHandler() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers MovLib\Exception\Handlers::uncaughtExceptionHandler
   * @todo   Implement testUncaughtExceptionHandler().
   */
  public function testUncaughtExceptionHandler() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}
