<?php

namespace MovLib\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-21 at 22:20:31.
 */
class HistoryExceptionTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var HistoryException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new HistoryException;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

}
