<?php

namespace MovLib\Presentation;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-21 at 22:20:34.
 */
class StacktraceTest extends \MovLib\TestCase {

  /**
   * @var Stacktrace
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
  /** @todo Implement properly. */
//    $this->object = new Stacktrace;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers MovLib\Presentation\Stacktrace::getPresentation
   * @todo   Implement testGetPresentation().
   */
  public function testGetPresentation() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers ::__construct
   * @todo Implement __construct
   */
  public function testConstruct() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

  /**
   * @covers ::formatStacktrace
   * @todo Implement formatStacktrace
   */
  public function testFormatStacktrace() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

  /**
   * @covers ::formatFunctionArguments
   * @todo Implement formatFunctionArguments
   */
  public function testFormatFunctionArguments() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

  /**
   * @covers ::formatClassName
   * @todo Implement formatClassName
   */
  public function testFormatClassName() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

  /**
   * @covers ::formatFileName
   * @todo Implement formatFileName
   */
  public function testFormatFileName() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

  /**
   * @covers ::formatLineNumber
   * @todo Implement formatLineNumber
   */
  public function testFormatLineNumber() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

  /**
   * @covers ::formatFunction
   * @todo Implement formatFunction
   */
  public function testFormatFunction() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

  /**
   * @covers ::formatFunctionType
   * @todo Implement formatFunctionType
   */
  public function testFormatFunctionType() {
    $this->markTestIncomplete("This test has not been implemented yet.");
  }

}
