<?php

namespace MovLib\Data\Delayed;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-21 at 22:20:38.
 */
class LoggerTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Logger
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Logger;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers MovLib\Data\Delayed\Logger::run
   * @todo   Implement testRun().
   */
  public function testRun() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers MovLib\Data\Delayed\Logger::stack
   * @todo   Implement testStack().
   */
  public function testStack() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}
