<?php

namespace MovLib\Data\Delayed;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-21 at 22:20:38.
 */
class MailerTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Mailer
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Mailer;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers MovLib\Data\Delayed\Mailer::send
   * @todo   Implement testSend().
   */
  public function testSend() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers MovLib\Data\Delayed\Mailer::run
   * @todo   Implement testRun().
   */
  public function testRun() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers MovLib\Data\Delayed\Mailer::stack
   * @todo   Implement testStack().
   */
  public function testStack() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}
