<?php

namespace MovLib\Presentation;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-10-21 at 22:20:34.
 */
class StacktraceTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Stacktrace
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Stacktrace;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers MovLib\Presentation\Stacktrace::getPresentation
   * @todo   Implement testGetPresentation().
   */
  public function testGetPresentation() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}
