#! /bin/bash
### BEGIN INIT INFO
# Provides:          memcached
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: memcached - Memory caching daemon
# Description:       memcached - Memory caching daemon
### END INIT INFO

# ----------------------------------------------------------------------------------------------------------------------
# This file is part of {@link https://github.com/MovLib MovLib}.
#
# Copyright © 2013-present {@link http://movlib.org/ MovLib}.
#
# MovLib is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public
# License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# MovLib is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY# without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with MovLib.
# If not, see {@link http://www.gnu.org/licenses/ gnu.org/licenses}.
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# Memcached init script, this script is based on the init script that comes along with the Memcached source download.
#
# AUTHOR: Richard Fussenegger <richard@fussenegger.info>
# COPYRIGHT: © 2013-present, MovLib
# LICENSE: http://www.gnu.org/licenses/agpl.html AGPL-3.0
# SINCE: 0.0.1-dev
# ----------------------------------------------------------------------------------------------------------------------

# Usage:
# start all instances:
# /etc/init.d/memcached start
# start one instance:
# /etc/init.d/memcached start server-1
# stop all instances:
# /etc/init.d/memcached stop
# stop one instance:
# /etc/init.d/memcached stop server-1
# There is no "status" command.

FILES=$(find -L /etc/memcached -iname '*.conf')
DAEMON=/usr/local/bin/memcached
DAEMONNAME=memcached

test -x $DAEMON || exit 0
set -e

if [ -r "${FILES[0]}" ]; then
  SERVERS=()
  for FILE in "${FILES[@]}";
  do
    # get the configuration files content
    PARAMS=$(cat $FILE)
    # remove all comments from the file and linearize the content to a single line
    PARAMS=$(grep -v '^#.*' < $FILE | tr '\n' ' ')
    # remove prefix
    NAME=${FILE#/etc/memcached/}
    # remove suffix
    NAME=${NAME%.conf}

    # check optional second param
    if [ $# -ne 2 ];
    then
      # add to config array
      SERVERS+=($NAME)
    elif [ "$2" == "$NAME" ];
    then
      # use only one memcached
      SERVERS=($NAME)
      break;
    fi;
  done;

  if [ ${#SERVERS[@]} == 0 ];
  then
    echo "Config for $2 does not exist!" >&2
    exit 1
  fi;
else
  echo "Could not find any memcached configuration files."
  exit 1
fi;

SERVER_COUNT=${#SERVERS[@]}
for ((i=0; i < $SERVER_COUNT; i++)); do
  NAME=${SERVERS[${i}]}
  PIDFILE="/run/memcached/${NAME}.pid"
  SOCKETFILE="/run/memcached/${NAME}.sock"
  USER=$(grep '^-u .*$' < /etc/memcached/${NAME}.conf | cut -d ' ' -f 2)
  PARAMS+=" -s $SOCKETFILE -P $PIDFILE -d"

  # Create the Memcached directory within the run directory and set appropriate permissions
  install --owner=$USER --directory /run/memcached

  case "$1" in
    start)
      echo -n "Starting $DAEMONNAME: "
      start-stop-daemon --start --quiet --exec "$DAEMON" -- $PARAMS
      echo "$NAME."
      ;;

    stop)
      echo -n "Stopping $DAEMONNAME: "
      start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
      echo "$NAME."
      rm -f $PIDFILE $SOCKETFILE
      ;;

    restart|force-reload)
      echo -n "Restarting $DAEMONNAME: "
      start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
      rm -f $PIDFILE $SOCKETFILE
      sleep 1
      start-stop-daemon --start --quiet --exec "$DAEMON" -- $PARAMS
      echo "$NAME."
      ;;

    *)
      N=/etc/init.d/$NAME
      echo "Usage: $N {start|stop|restart|force-reload}" >&2
      exit 1
      ;;
  esac
done;

exit 0
